# Generated by Django 3.0.9 on 2021-12-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0037_edit_page_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('intime', models.TimeField(blank=True, null=True)),
                ('outtime', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
