# Generated by Django 3.2.10 on 2021-12-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0038_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit_page',
            name='file',
            field=models.FileField(blank=True, null=True, unique=True, upload_to=''),
        ),
    ]
