# Generated by Django 4.0 on 2022-01-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0040_alter_edit_page_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='gst_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('legal_name', models.CharField(max_length=100, null=True)),
                ('trade_name', models.CharField(max_length=100, null=True)),
                ('gst_no', models.CharField(max_length=100, null=True)),
                ('gst_username', models.CharField(max_length=100, null=True)),
                ('gst_pwd', models.CharField(max_length=100, null=True)),
                ('pan_no', models.CharField(max_length=100, null=True)),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('org', models.CharField(max_length=100, null=True)),
                ('con_person', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('address1', models.CharField(max_length=1000, null=True)),
                ('address2', models.CharField(max_length=1000, null=True)),
                ('email1', models.EmailField(max_length=254, null=True)),
                ('email2', models.EmailField(max_length=254, null=True)),
                ('pincode', models.IntegerField()),
                ('phone', models.IntegerField(max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='doc',
        ),
    ]
