# Generated by Django 4.0 on 2022-01-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0044_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='priority',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
