# Generated by Django 4.0 on 2022-01-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0045_tasklist_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='priority',
        ),
    ]
