# Generated by Django 4.0 on 2022-01-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0050_alter_tasklist_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='company',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
