# Generated by Django 4.0 on 2022-01-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0052_alter_tasklist_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='company',
        ),
    ]
