# Generated by Django 4.0 on 2022-01-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0053_remove_tasklist_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='company',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
