# Generated by Django 4.0 on 2022-01-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0055_remove_tasklist_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='priority',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
