# Generated by Django 4.0 on 2022-01-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0056_tasklist_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100, null=True)),
                ('client', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('work_from', models.TimeField(blank=True, null=True)),
                ('work_to', models.TimeField(blank=True, null=True)),
                ('file', models.FileField(default=True, upload_to='')),
            ],
        ),
    ]
