# Generated by Django 4.0 on 2022-02-08 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0061_client_address1_client_address2_client_c_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='client',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='client',
            name='c_no',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cc',
        ),
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='client',
            name='res_per_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='state',
        ),
    ]
